const mongoose = require('mongoose');
const Certificate = require('../models/Certificate');
require('dotenv').config();

const analyzeCertificates = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/certificate-verification');
    
    const certs = await Certificate.find({});
    console.log('Certificate analysis:');
    certs.forEach((cert, i) => {
      console.log(`${i+1}. ${cert.studentName} - ${cert.courseName}`);
      console.log(`   ID: ${cert._id}`);
      console.log(`   Language: ${cert.language || 'english'}`);
      console.log(`   Auto-generated: ${cert.certificateData?.autoGenerated || false}`);
      if (cert.certificateData?.teacherName) {
        console.log(`   Teacher: ${cert.certificateData.teacherName}`);
      }
      if (cert.certificateData?.template) {
        console.log(`   Template: ${cert.certificateData.template}`);
      }
      console.log('');
    });
    
    await mongoose.disconnect();
  } catch (error) {
    console.error('Error:', error);
  }
};

analyzeCertificates();