console.log('📧 GMAIL APP PASSWORD SETUP GUIDE');
console.log('==================================');
console.log('');
console.log('🚨 IMPORTANT: You cannot use your regular Gmail password!');
console.log('   Gmail requires a special "App Password" for email sending.');
console.log('');
console.log('📋 STEP-BY-STEP INSTRUCTIONS:');
console.log('');
console.log('1. 🔐 ENABLE 2-FACTOR AUTHENTICATION:');
console.log('   • Go to: https://myaccount.google.com/');
console.log('   • Click "Security" on the left');
console.log('   • Find "2-Step Verification" and enable it');
console.log('   • You\'ll need your phone for verification');
console.log('');
console.log('2. 🔑 GENERATE APP PASSWORD:');
console.log('   • Still in "Security" section');
console.log('   • Scroll down to "App passwords"');
console.log('   • Click "App passwords"');
console.log('   • You might need to sign in again');
console.log('   • Select "Mail" from dropdown');
console.log('   • Click "Generate"');
console.log('   • Copy the 16-character password (like: abcd efgh ijkl mnop)');
console.log('');
console.log('3. 📝 UPDATE .ENV FILE:');
console.log('   • Open backend/.env');
console.log('   • Replace EMAIL_APP_PASSWORD with the 16-character password');
console.log('   • Example: EMAIL_APP_PASSWORD=abcdefghijklmnop');
console.log('');
console.log('4. 🔄 RESTART BACKEND SERVER:');
console.log('   • Stop current server (Ctrl+C)');
console.log('   • Start again: npm start');
console.log('');
console.log('5. 🧪 TEST EMAIL:');
console.log('   • Run: node scripts/quickEmailTest.js');
console.log('');
console.log('⚠️  COMMON MISTAKES:');
console.log('   ❌ Using regular Gmail password');
console.log('   ❌ Not enabling 2-Factor Authentication first');
console.log('   ❌ Including spaces in App Password');
console.log('   ❌ Not restarting server after changing .env');
console.log('');
console.log('✅ CORRECT FORMAT:');
console.log('   EMAIL_USER=Periyanayagi25041974@gmail.com');
console.log('   EMAIL_APP_PASSWORD=abcdefghijklmnop  (16 characters, no spaces)');
console.log('');
console.log('🎯 AFTER SETUP:');
console.log('   • Students will receive emails automatically');
console.log('   • You\'ll see "✅ Certificate email sent successfully!" in logs');
console.log('   • Emails include certificate details and verification links');
console.log('');
console.log('📞 NEED HELP?');
console.log('   If you get "Invalid login" error, double-check:');
console.log('   1. 2FA is enabled on Gmail');
console.log('   2. Using App Password (not regular password)');
console.log('   3. No typos in email or password');
console.log('   4. Server was restarted after .env changes');
console.log('');
console.log('🚀 Ready to set up Gmail App Password? Follow the steps above!');