const mongoose = require('mongoose');
const axios = require('axios');
const User = require('../models/User');
const Certificate = require('../models/Certificate');
require('dotenv').config();

const API_BASE = 'http://localhost:5000/api';

const testEverything = async () => {
  try {
    console.log('🔄 Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/certificate-verification');
    console.log('✅ Connected to MongoDB');

    // Test 1: Check users
    console.log('\n📋 Testing Users...');
    const users = await User.find({});
    console.log(`Found ${users.length} users:`);
    users.forEach(user => {
      console.log(`- ${user.name} (${user.email}) - Role: ${user.role}`);
    });

    // Test 2: Check certificates
    console.log('\n📜 Testing Certificates...');
    const certificates = await Certificate.find({});
    console.log(`Found ${certificates.length} certificates:`);
    certificates.forEach(cert => {
      console.log(`- ${cert.studentName}: ${cert.courseName} (${cert.language || 'english'})`);
      if (cert.certificateData?.autoGenerated) {
        console.log(`  ↳ Auto-generated by ${cert.certificateData.teacherName}`);
      }
    });

    // Test 3: Login as institution
    console.log('\n🔐 Testing Institution Login...');
    try {
      const loginRes = await axios.post(`${API_BASE}/auth/login`, {
        email: 'institution@demo.com',
        password: 'password123'
      });
      
      const institutionToken = loginRes.data.token;
      console.log('✅ Institution login successful');

      // Test 4: Fetch institution certificates
      console.log('\n📊 Testing Institution Dashboard...');
      const certRes = await axios.get(`${API_BASE}/certificates/institution`, {
        headers: { Authorization: `Bearer ${institutionToken}` }
      });
      
      console.log(`Institution has ${certRes.data.certificates.length} certificates:`);
      certRes.data.certificates.forEach(cert => {
        console.log(`- ${cert.studentName}: ${cert.courseName}`);
      });

      // Test 5: Fetch institution stats
      const statsRes = await axios.get(`${API_BASE}/certificates/institution/stats`, {
        headers: { Authorization: `Bearer ${institutionToken}` }
      });
      
      console.log('Institution stats:', statsRes.data);

    } catch (error) {
      console.error('❌ Institution login failed:', error.response?.data || error.message);
    }

    // Test 6: Login as student
    console.log('\n👨‍🎓 Testing Student Login...');
    try {
      const studentLoginRes = await axios.post(`${API_BASE}/auth/login`, {
        email: 'student1@demo.com',
        password: 'password123'
      });
      
      const studentToken = studentLoginRes.data.token;
      console.log('✅ Student login successful');

      // Test 7: Fetch student certificates
      console.log('\n📋 Testing Student Dashboard...');
      const studentCertRes = await axios.get(`${API_BASE}/certificates/student`, {
        headers: { Authorization: `Bearer ${studentToken}` }
      });
      
      console.log(`Student has ${studentCertRes.data.certificates.length} certificates:`);
      studentCertRes.data.certificates.forEach(cert => {
        console.log(`- ${cert.courseName} from ${cert.institutionName}`);
      });

      // Test 8: Fetch student stats
      const studentStatsRes = await axios.get(`${API_BASE}/certificates/student/stats`, {
        headers: { Authorization: `Bearer ${studentToken}` }
      });
      
      console.log('Student stats:', studentStatsRes.data);

    } catch (error) {
      console.error('❌ Student login failed:', error.response?.data || error.message);
    }

    // Test 9: Test multilingual languages endpoint
    console.log('\n🌍 Testing Multilingual Features...');
    try {
      const langRes = await axios.get(`${API_BASE}/multilingual-certificates/languages`);
      console.log(`Supported languages: ${langRes.data.languages.length}`);
      console.log('Languages:', langRes.data.languages.map(l => l.name).join(', '));
    } catch (error) {
      console.error('❌ Multilingual test failed:', error.response?.data || error.message);
    }

    // Test 10: Test auto-certificate templates
    console.log('\n🤖 Testing Auto-Certificate Features...');
    try {
      const templatesRes = await axios.get(`${API_BASE}/auto-certificates/templates`);
      console.log(`Available templates: ${templatesRes.data.templates.length}`);
      console.log('Templates:', templatesRes.data.templates.map(t => t.name).join(', '));
    } catch (error) {
      console.error('❌ Auto-certificate test failed:', error.response?.data || error.message);
    }

    console.log('\n🎉 All tests completed!');

  } catch (error) {
    console.error('❌ Test failed:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
};

testEverything();