const axios = require('axios');
const fs = require('fs');
const mongoose = require('mongoose');
const Certificate = require('../models/Certificate');
require('dotenv').config();

const API_BASE = 'http://localhost:5000/api';

const testDownload = async () => {
  try {
    console.log('🔄 Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/certificate-verification');
    console.log('✅ Connected to MongoDB');

    // Get sample certificates
    const certificates = await Certificate.find({}).limit(3);
    console.log(`Found ${certificates.length} certificates for testing`);

    // Test 1: Login as institution
    console.log('\n🔐 Logging in as institution...');
    const loginRes = await axios.post(`${API_BASE}/auth/login`, {
      email: 'institution@demo.com',
      password: 'password123'
    });
    
    const token = loginRes.data.token;
    console.log('✅ Institution login successful');

    // Test 2: Try downloading each certificate
    for (let i = 0; i < certificates.length; i++) {
      const cert = certificates[i];
      console.log(`\n📄 Testing download for certificate ${i + 1}:`);
      console.log(`Student: ${cert.studentName}, Course: ${cert.courseName}`);
      console.log(`Language: ${cert.language || 'english'}`);
      console.log(`Auto-generated: ${cert.certificateData?.autoGenerated || false}`);

      try {
        const response = await axios.get(
          `${API_BASE}/certificates/${cert._id}/download`,
          {
            headers: { Authorization: `Bearer ${token}` },
            responseType: 'arraybuffer'
          }
        );

        console.log('✅ Download successful');
        console.log(`Content-Type: ${response.headers['content-type']}`);
        console.log(`Content-Length: ${response.data.length} bytes`);

        // Save to file for verification
        const filename = `test-certificate-${i + 1}.pdf`;
        fs.writeFileSync(filename, response.data);
        console.log(`📁 Saved as: ${filename}`);

      } catch (error) {
        console.error('❌ Download failed:', error.response?.status, error.response?.statusText);
        if (error.response?.data) {
          console.error('Error details:', Buffer.from(error.response.data).toString());
        }
      }
    }

    // Test 3: Login as student and try download
    console.log('\n👨‍🎓 Testing student download...');
    const studentLoginRes = await axios.post(`${API_BASE}/auth/login`, {
      email: 'student1@demo.com',
      password: 'password123'
    });
    
    const studentToken = studentLoginRes.data.token;
    console.log('✅ Student login successful');

    // Find a certificate for this student
    const studentCert = certificates.find(cert => cert.studentEmail === 'student1@demo.com');
    if (studentCert) {
      console.log(`\n📄 Testing student download for: ${studentCert.courseName}`);
      
      try {
        const response = await axios.get(
          `${API_BASE}/certificates/${studentCert._id}/download`,
          {
            headers: { Authorization: `Bearer ${studentToken}` },
            responseType: 'arraybuffer'
          }
        );

        console.log('✅ Student download successful');
        console.log(`Content-Length: ${response.data.length} bytes`);

        // Save to file
        fs.writeFileSync('test-student-certificate.pdf', response.data);
        console.log('📁 Saved as: test-student-certificate.pdf');

      } catch (error) {
        console.error('❌ Student download failed:', error.response?.status, error.response?.statusText);
      }
    }

    console.log('\n🎉 Download tests completed!');

  } catch (error) {
    console.error('❌ Test failed:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
};

testDownload();